### ISSUE TITLE
LUTs location

### ISSUE THREAD

**Issue by formulake** [cubiq/ComfyUI_essentials#15]
I have a bunch of CUBE files that I use with the LUTs node from the Bilbox collection and they are detected and work just fine there. I placed them in the luts folder in ComfyUI Essentials because I want to reduce the number of extensions with overlapping functions I have. UNfortunately I have refreshed and restarted multiple times but the files fail to be recognised by the ComfyUI Essentials LUTs node. Am I missing something. On a side note, I really appreciate your work. Thank you for the tremendous value you provide to the community.

**Comment by cubiq** [comment]
luts files should go in the ComfyUI_essentials/luts/ folder. if they are not recognized try to remove the bilbox extension and use lowercase for the extension (.cube)

**Comment by formulake** [comment]
> luts files should go in the ComfyUI_essentials/luts/ folder. if they are not recognized try to remove the bilbox extension and use lowercase for the extension (.cube)

Renaming the file type to lowercase ".cube" did the trick. Did that first and didn't have to delete the Bilbox node group, for anybody else who faces this issue. Thanks very much for the solution and the super-quick response!
