### ISSUE TITLE
Possible to add "crop" to Image Resize node?

### ISSUE THREAD

**Issue by mocmocmoc** [cubiq/ComfyUI_essentials#19]
For resizing and cropping an image so both the width and height are multiple of 64.

Currently I'm using something like this:
<img width="1021" alt="Screenshot 2024-03-16 181139" src="https://github.com/cubiq/ComfyUI_essentials/assets/6404011/40f576e5-698e-4c65-a382-3e696b46976f">

Thanks.

**Comment by cubiq** [comment]
good point. I'll work on that

**Comment by cubiq** [comment]
this is now available
