### ISSUE TITLE
feat: ImageResize: total number of pixels as alternative to size

### ISSUE THREAD

**Issue by bigcat88** [cubiq/ComfyUI_essentials#22]
The first thing I would like to say is: Thank you very much for your work, the nodes are very useful

Is it possible to add the total number of pixels to the ImageResize node as an alternative to width and height?

The situation is as follows: we have an upscaler workflow on Suprim, we need to downscale if the image is larger than a certain size.

Using width and height in this case is less convenient than the total number of pixels - it greatly cuts images in 16:9 format, when based on the total number of pixels such images would pass without resizing.

**Comment by cubiq** [comment]
can you use "only if bigger/smaller" option?

**Comment by bigcat88** [comment]
> can you use "only if bigger/smaller" option?

yes, we use the “only if bigger” option and for 1:1 aspect images it works great, but for 16:9 images (1280x720) it will take the larger of the sides and apply scaling, and we have a limit on the total number of pixels, and 1280x720 fit in that number and should not be downscaled in out case.
but 1100x1100 resolution does not fit and should be downscaled.

**Comment by cubiq** [comment]
I added a condition by "area" I think this is what you needed
