### ISSUE TITLE
Image Crop+ not working

### ISSUE THREAD

**Issue by kakachiex2** [cubiq/ComfyUI_essentials#28]
Image Crop+ not working as you can see in the screenshot.
![Screenshot 2024-04-27 023948](https://github.com/cubiq/ComfyUI_essentials/assets/1762112/bf56383a-e8c8-4f58-b925-fafe33fdd91c)

**Comment by cubiq** [comment]
the image might be smaller than 1024 on any side maybe

**Comment by kakachiex2** [comment]
let me see

**Comment by kakachiex2** [comment]
Yes, looks like the image was too small, thanks!
