### ISSUE TITLE
Tensor Debug Missing

### ISSUE THREAD

**Issue by wperrin** [cubiq/ComfyUI_essentials#31]
Watching your videos, I was hoping to be able to use the Tenser debug to view the sizes of my clip inputs. Do you have a new improved method for viewing those?

**Comment by cubiq** [comment]
yeah I think it can be improved to add those as well

**Comment by wperrin** [comment]
It looks like perhaps you had this class in your original version of essentials. Did it get removed later?

**Comment by cubiq** [comment]
it's still there, it's called "tensor shape debug"
