### ISSUE TITLE
msak preview :No preview properties are displayed

### ISSUE THREAD

**Issue by mikko66** [cubiq/ComfyUI_essentials#35]
Hello blogger, as shown in the picture, I used the MASK preview node and the prompt was no preview property. I updated comfyui and the system, but couldn't fix the problem. I downloaded a new node (ComfyUI_essentials) to upload the same error. Can you help me see what went wrong? Thank you very much. Puzzled me for a long time.
![下载](https://github.com/cubiq/ComfyUI_essentials/assets/167275411/86111965-4eda-4e72-9650-b6f99d4d8c3a)

**Comment by mikko66** [comment]
Error occurred when executing MaskPreview+:

'MaskPreview' object has no attribute 'preview'

File "/code/ComfyUI/execution.py", line 155, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/code/ComfyUI/execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/code/ComfyUI/execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/code/ComfyUI/custom_nodes/ComfyUI_essentials/essentials.py", line 447, in execute
return self.save_images(preview, filename_prefix, prompt, extra_pnginfo)
File "/code/ComfyUI/nodes.py", line 1478, in save_images
if not self.preview:

**Comment by cubiq** [comment]
try to upgrade comfy
