### ISSUE TITLE
Ksampler with noise injection  is broken

### ISSUE THREAD

**Issue by Creative-comfyUI** [cubiq/ComfyUI_essentials#37]
Hi Matteo

Everything was fine with the ksampler with noise injection. The next day nothing worked, it gives black images for the same setting. There's no error message in the terminal and all updates do nothing. It only works for a batch size of 1 over we have black image. Moreover, for the same seed and the same parameters, the image with batch size 1 doesn't give the same image as before.
What could be the problem? 

Just for your information before updating I have time to time in the terminal this error.  Now it has disappeared, I don't know if it is related to your ksampler.  
'## sdxl-ksample [3c7e70]' is broken. Maybe there are missing nodes. (INFO: ### [ERROR] "Multiply" node is not installed. Please install that node through ComfyUI-Mananger. ###)   

Thank you

**Comment by cubiq** [comment]
I'm working on an update to the essentials, I will check this too

**Comment by Creative-comfyUI** [comment]
Thank you Matteo. In my opinion your Ksampler is the way Ksampler should work. ComfyUI ksampler add a x% noise variation to image which is not the case with yours which give more control on the image. If we take the case of Euler for a batch size of 3 we have the same 3 images which is what should be but this is not the case with the ksampler of comfyUI. 
Another point. I understand that each sampler except Euler and Dimm inject a x% of noise. I assume this is not random it is calculated.  If I am correct the seed is good for the first image but the ones that follow have a x% injection, can we get this new seed for each one that follows the first image? Or do you have a link with the formulation ?

**Comment by cubiq** [comment]
okay I had a look at the code and everything seems to be working as it should both sdxl and sd1.5

can I see a minimal workflow that causes this issue?

**Comment by Creative-comfyUI** [comment]
The bug comes from comfyUI. I was not the only one to have this problem. Users on Mac have this problem too after the update. Two days ago everything is working again and the workflow renders the image as before.
