### ISSUE TITLE
ComfyUI Manager can't update this repo

### ISSUE THREAD

**Issue by LukeG89** [cubiq/ComfyUI_essentials#39]
Hi, I just pulled an update from ComfyUI Manager and this is the only repo it can't upgrade.

I also used the "try update" button, but it gave me this error:

![update_error](https://github.com/cubiq/ComfyUI_essentials/assets/161304036/7f7f0a7b-88ce-4d59-a593-067a74fbf461)

(I'm also worried about that error because there's my full name twice under those red lines... How did it get that!? 😟)

**Comment by LukeG89** [comment]
Hi Matteo, I don't know why but it keeps throwing me an error when updating with the manager:

![failed_update](https://github.com/cubiq/ComfyUI_essentials/assets/161304036/f65978b6-68e1-47eb-abda-84c1ef3ea811)

**Comment by cubiq** [comment]
I had an error yesterday with the commit, you got caught in the cross-fire while I was fixing it :smile:  . If you delete the node now and reinstall it, it won't give you more issues in the future

**Comment by LukeG89** [comment]
Ok, now seems fixed! Thanks again! 😄
