### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by fresno808** [cubiq/ComfyUI_essentials#46]
It seems like after the latest update of essentials, I keep getting this error.
![boolerror](https://github.com/cubiq/ComfyUI_essentials/assets/158516225/85ed718c-db61-4192-88ce-bc9823bc50b6)

**Comment by cubiq** [comment]
delete the node and recreate it

**Comment by fresno808** [comment]
hello, I tried that but im still getting the same error regarding resize+

**Comment by fresno808** [comment]
i was able to fix it, ty!
