### ISSUE TITLE
Error when updating 

### ISSUE THREAD

**Issue by JorgeR81** [cubiq/ComfyUI_essentials#49]
I'm getting an error when updating, via Manager. 

I'm on Windows 10. 

![cuie1](https://github.com/cubiq/ComfyUI_essentials/assets/72734038/6c438ee4-f34e-43a5-a4cb-8d988958793b)

**Comment by cubiq** [comment]
delete the directory and reinstall

**Comment by agarzon-orangerine** [comment]
having the same issue. `delete the directory and reinstall` solved. 😀

**Comment by JorgeR81** [comment]
I can't be 100% sure it's working, because there have been no updates yesterday, for Comfy UI_essentials.

But, it's probably fixed, since I don't have the error message anymore. 

![cui2](https://github.com/cubiq/ComfyUI_essentials/assets/72734038/bf6324b7-aacd-448b-830e-25bb767f695c)

**Comment by JorgeR81** [comment]
After reinstalling, it updates correctly now. 
So, I'm closing this.  

![cue](https://github.com/cubiq/ComfyUI_essentials/assets/72734038/c9ec606e-4e46-41d5-995c-00bd5e01c9f2)
