### ISSUE TITLE
节点成功安装了，但是在进入comfyui后还是调用不了节点，判断节点缺失，但在管理器中节点又显示是安装好的

### ISSUE THREAD

**Issue by 0451G** [cubiq/ComfyUI_essentials#55]
节点成功安装了，但是在进入comfyui后还是调用不了节点，判断节点缺失，但在管理器中节点又显示是安装好的

**Comment by cubiq** [comment]
I would need to see the console if there are any errors

**Comment by 0451G** [comment]
解决了，在使用整合包时，不知道为什么整合包中缺少了node_helpers.py这个文件，造成节点在import时出错，影响了节点使用，感谢关注

**Comment by zhuxianhong0** [comment]
> 解决了，在使用整合包时，不知道为什么整合包中缺少了node_helpers.py这个文件，造成节点在import时出错，影响了节点使用，感谢关注

Where to download this file, and where to put it after downloading?

**Comment by cubiq** [comment]
you to upgrade comfyui

**Comment by 0451G** [comment]
> > 解决了，在使用整合包时，不知道为什么整合包中缺少了node_helpers.py这个文件，造成节点在import时出错，影响了节点使用，感谢关注
> 
> Where to download this file, and where to put it after downloading?

在github，comfyui项目源文件中下载node_helpers.py，放在你comfyui根目录

**Comment by zzzSEA** [comment]
老哥，我也有同样的问题，但是我的启动器的检查并未检查出依赖缺失，我是缺失安装好后文件存在，但是检查的时候仍然显示为缺失节点，缺失节点旁边显示为更新、卸载，而不是安装
