### ISSUE TITLE
Mask Blur changes

### ISSUE THREAD

**Issue by Davikar** [cubiq/ComfyUI_essentials#6]
Mask blur used to blur the outer regions of the mask, but now it blurs the entire mask.
While this change was probably intended, I prefer the old behaviour. Maybe we can get a new node that works like before?

**Comment by cubiq** [comment]
the way the mask is applied shouldn't have changed... I'll check later, what's the difference that you are noticing again? Can you post an example?

**Comment by Davikar** [comment]
<img width="1091" alt="image" src="https://github.com/cubiq/ComfyUI_essentials/assets/8229634/187a04fb-0491-44c9-b9ba-599b3e7e9f7e">

As you can see the entire mask is blurred. Unless I remember wrong, only the edges were blurred before?

**Comment by cubiq** [comment]
as I can tell, this is the right behavior :smile:  By edges you mean corners?

60 is a very big value for blur, if you set it to like 20 it should look exactly like before

**Comment by Davikar** [comment]
Hmm, yeah, you're right. Somehow I can't seem to reproduce what I saw before. I must have done something weird... 😛 
Sorry about that. I'll close this issue.
