### ISSUE TITLE
Can't see "Image Tile+" and "Color Match" nodes

### ISSUE THREAD

**Issue by sdk401** [cubiq/ComfyUI_essentials#60]
No errors on install and on load, but nodes are not in the list, and if I load a workflow with them, they give an missing node error.

![image](https://github.com/user-attachments/assets/87a36c72-1622-440f-b4eb-e4614ada0b12)

When I go to "install missing nodes" in manager, it shows that the node pack is installed, and no conflicts.

![image](https://github.com/user-attachments/assets/04266f5c-15df-4845-9f48-45f6db64e33c)

Tried reinstalling many times, no effect.
Maybe some packages are missing, but no errors in the log, so can't know which ones.

**Comment by cubiq** [comment]
try in incognito mode, if it works it's a browser cache issue

**Comment by sdk401** [comment]
> try in incognito mode, if it works it's a browser cache issue

not working :(
made a fresh install and it works. must be some conflict with other nodes. will have to install one by one and find the culprit, i guess.
