### ISSUE TITLE
Show text node

### ISSUE THREAD

**Issue by sahuhtala** [cubiq/ComfyUI_essentials#64]
Please consider adding a simple "Show text" node to the node package.

At the moment the most used node for that seem to be from [pythongosssss/ComfyUI-Custom-Scripts](https://github.com/pythongosssss/ComfyUI-Custom-Scripts), but that package doesn't play well with the "vanilla" ComfyUI experience as it forces a lot of changes to the base UI.

I believe showing the contents of a string truly is an essential feature that's currently missing from ComfyUI.

Example:
![image](https://github.com/user-attachments/assets/cb550181-ea1f-497a-a850-bb53c4fdf507)

**Comment by cubiq** [comment]
yeah I agree it's a useful node, I'll think about it

**Comment by cubiq** [comment]
I added the DisplayAny node that can display anything

**Comment by sahuhtala** [comment]
Amazing, thank you!
