### ISSUE TITLE
Flux Sampler Parameters "noise" field should be "seed" (I think)

### ISSUE THREAD

**Issue by ricperry** [cubiq/ComfyUI_essentials#67]
![image](https://github.com/user-attachments/assets/096be8ec-1e4e-4b42-a1fb-7eb428c59dee)
Also, "sampler" and "scheduler" are not drop-downs, so I have to manually type the sampler and scheduler to use.

**Comment by ricperry** [comment]
Probably my misunderstanding on how to use this node.

**Comment by cubiq** [comment]
I'll write some documentation. you can join my discord in the meantime if you need some help https://discord.com/invite/W2DhHkcjgn
