### ISSUE TITLE
ModuleNotFoundError: No module named 'comfy_extras.nodes_stable3d

### ISSUE THREAD

**Issue by jvalo-arts** [cubiq/ComfyUI_essentials#7]
This node pack is currently not working for me when downloaded through the manager.

"(IMPORT FAILED) [ComfyUI Essentials](https://github.com/cubiq/ComfyUI_essentials)"

File "C:\Program Files\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials\essentials.py", line 730, in <module>
    from comfy_extras.nodes_stable3d import camera_embeddings
ModuleNotFoundError: No module named 'comfy_extras.nodes_stable3d'

Cannot import C:\Program Files\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials module for custom nodes: No module named 'comfy_extras.nodes_stable3d'

The issue gets resolved if I delete the part about StableZero123_Increments from essentials.py

**Comment by ninjavfx** [comment]
Same here

**Comment by cubiq** [comment]
you need to update comfyui

**Comment by jvalo-arts** [comment]
Thanks! Updating solved the problem. I thought I had been updating comfy but it turns out I had only been updating custom nodes. Still learning :)
