### ISSUE TITLE
[Bug] Broken SimpleMath+ Node after update

### ISSUE THREAD

**Issue by Steudio** [cubiq/ComfyUI_essentials#70]
![image](https://github.com/user-attachments/assets/e926bd5f-a92f-4bb2-9189-3bf6035e3587)

**Comment by cubiq** [comment]
use simplemath as variable, just put the value that you need in a simplemath node and you can use that as variable for other simplemath nodes

**Comment by Steudio** [comment]
Just so I understand correctly, like this ?
![image](https://github.com/user-attachments/assets/9635192b-e73d-48c9-9f44-131fc65d25b8)
same error message

**Comment by cubiq** [comment]
![image](https://github.com/user-attachments/assets/7d098584-663c-4e3a-9dac-fe92ab83afb3)

**Comment by Steudio** [comment]
Still doesn't work on my end.

**Comment by cubiq** [comment]
okay today's version of Comfy broke it... should be easy to fix, need to check what changed

**Comment by GinCanhViet** [comment]
Hope it gets fixed soon

![image](https://github.com/user-attachments/assets/2bda09f6-231c-4583-a745-474dfd13e5fd)

**Comment by cubiq** [comment]
should be fixed

**Comment by blazeclark** [comment]
Hey! Days ago, I faced the same problem. Now I've found another node that looks like it's working:
![Screenshot 2024-08-19 131056](https://github.com/user-attachments/assets/04156973-3887-41c4-bb28-3a684632aabd)

**Comment by gary0318** [comment]
I am having this issue no matter what simple math node I use. Including the last one mentioned above. I see that this is closed, but didn't see a final resolution. I've updated comfyui to the latest and it hasn't helped. Is there a solution?

**Comment by cubiq** [comment]
What is the problem again? Everything seems to be working. Please open a new issue with detailed instruction to replicate
![image](https://github.com/user-attachments/assets/acbf1c28-81da-4b1a-892b-94e117b965b5)

**Comment by levanly2506** [comment]
![Screenshot 2024-09-12 232050](https://github.com/user-attachments/assets/05beb370-e71c-472c-bbf5-739e70da9694)


> > Hope it gets fixed soon
> > ![image](https://private-user-images.githubusercontent.com/22634754/358458006-2bda09f6-231c-4583-a745-474dfd13e5fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNTc4NzYsIm5iZiI6MTcyNjE1NzU3NiwicGF0aCI6Ii8yMjYzNDc1NC8zNTg0NTgwMDYtMmJkYTA5ZjYtMjMxYy00NTgzLWE3NDUtNDc0ZGZkMTNlNWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDE2MTI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMDdmMWI1MTNlNWU0MTIwODVlMTk0ODkwZTNmZDBlNzQxYTk3M2QyYThmNzIwMTRjY2RhN2MzMDQ2MTU4NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cHzsfQYmhEW4PrBOYdn2JOz5W81WK3pE8ztgtDBDsrE)
> 
> I ALSO HAVE A SIMILAR SITUATION. IT STILL CAN'T BE FIXED

**Comment by Steudio** [comment]
I can confirm that Matteo fixed the issue I had 3 weeks ago.
Are you sure you are using the latest version? The new simple math node now has 3 inputs

**Comment by mariomorenobcn** [comment]
ComfyUI Manager Menu > "Update all". This solved the problem in my case....
