### ISSUE TITLE
"Flux Sampler Parameters" node should have selectable Sampler/Scheduler fields not, text.

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [cubiq/ComfyUI_essentials#71]
As per the title, these should have list of available options and not have to be typed in manually, which could lead to mistakes.
![image](https://github.com/user-attachments/assets/42afa704-a301-4ab2-a829-0ae3359ee78e)

**Comment by GalaxyTimeMachine** [comment]
Just realised this is likely meant to be this way so multiple options can be added. Please close if this is the case.

**Comment by cubiq** [comment]
yes, you can use multiple values separated by commas. there are a couple of helpers nodes to help pick the samplers/schedulers

![image](https://github.com/user-attachments/assets/6ea2aa2a-c7a0-4a37-bd8a-7203da3bd446)

**Comment by 6LAILAI** [comment]
![image](https://github.com/user-attachments/assets/0024aa4a-8eed-4fb0-9769-df354b8aa252)
发现没有sampler这个输入选项

**Comment by JaimeUtad** [comment]
Im new and i download the windows version and i dont got the Flux Sampler Parameters and i would like to have where can i download it? Thank you
