### ISSUE TITLE
Max_shift value is stuck on 0 in FluxSamplerParams+ node

### ISSUE THREAD

**Issue by 19KRO** [cubiq/ComfyUI_essentials#74]
Hi, 

I presume there is a bug in FluxSamplerParams+ node.
Although I change the value of Max_shift to ≠ 0 in the node, the terminal shows that Sampling starts with value 0. This happens no mater how I declare the value for the node.

`Loading 1 new model`
`WARNING: comfy_extras.chainner_models is deprecated and has been replaced by the spandrel library.`
`Sampling 1/1 with seed 1077394169247371, sampler euler_ancestral, scheduler beta, steps 4, guidance 1.8, max_shift 0, base_shift 0.8, denoise 0.45`

Thank you for your time,

![Screenshot 2024-08-18 at 13-01-46 ComfyUI](https://github.com/user-attachments/assets/e233cb69-31c5-4654-b209-bd314a9bbf71)
![Screenshot 2024-08-18 at 13-01-54 ComfyUI](https://github.com/user-attachments/assets/889b72b6-a227-431c-9177-d1a44f9a235f)
![Screenshot 2024-08-18 at 13-02-21 ComfyUI](https://github.com/user-attachments/assets/f8036132-5978-4a07-bbe9-5e0277005fd7)

**Comment by cubiq** [comment]
Schnell doesn't make use of max_shift but only base_shift, so the value is zeroed for schnell

**Comment by 19KRO** [comment]
Thank you very much for your quick answer. That fully resolves the question.
