### ISSUE TITLE
StableZero123_Increments:  The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1

### ISSUE THREAD

**Issue by RageshAntonyHM** [cubiq/ComfyUI_essentials#8]
When I try to input a generated image which background has been removed to StableZero123_Increments node, I am get this error:

Error occurred when executing StableZero123_Increments:

```
The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1

File "/workspace/ComfyUI/execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/workspace/ComfyUI/execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/workspace/ComfyUI/execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/workspace/ComfyUI/custom_nodes/ComfyUI_essentials/essentials.py", line 753, in encode
output = clip_vision.encode_image(init_image)
File "/workspace/ComfyUI/comfy/clip_vision.py", line 49, in encode_image
pixel_values = clip_preprocess(image.to(self.load_device)).float()
File "/workspace/ComfyUI/comfy/clip_vision.py", line 30, in clip_preprocess
return (image - mean.view([3,1,1])) / std.view([3,1,1])
```
I used https://github.com/Jcd1230/rembg-comfyui-node to remove background

But if I give it direct from "VAE Decode" then it is working. Why?

Please help me

My workflow image:
![workflow](https://github.com/cubiq/ComfyUI_essentials/assets/141845438/9fc7805b-a8f2-4120-b5d1-7d058e74f319)

Workflow JSON in attachment:
[sd_3d_bg_rem_steps.json](https://github.com/cubiq/ComfyUI_essentials/files/13758846/sd_3d_bg_rem_steps.json)

**Comment by cubiq** [comment]
I don't think turbo supports alpha. you need to combine the alpha image with a white image

**Comment by RageshAntonyHM** [comment]
@cubiq 

You mean to use a pure white background instead of transparent alpha?

**Comment by cubiq** [comment]
yes

![image](https://github.com/cubiq/ComfyUI_essentials/assets/427614/cfbc3c5f-3d78-4b93-be2d-7b885a226228)
