### ISSUE TITLE
Why string inputs for Flux Sampler Parameters !?

### ISSUE THREAD

**Issue by tetsuoo-online** [cubiq/ComfyUI_essentials#83]
For some reason, it's like this ? Not convenient to custiomize with other nodes :/ That would force me to use tons of converters
![image](https://github.com/user-attachments/assets/e6ff67f5-d9f8-4aa0-b9af-a255931cf046)

**Comment by cubiq** [comment]
because you can enter multiple parameters, like guidance `3, 3.5, 4` and the sampler will generate 3 images
