### ISSUE TITLE
How do I find the actual seed used when set to random ( ? ) ? 

### ISSUE THREAD

**Issue by gonzalu** [cubiq/ComfyUI_essentials#84]
Using the Flux Sampler Params node, I always wondered how to tell what actual seed was used? If I drag and drop the generated image with workflow embedded back into ComfyUI, the image is [not] reproduced exactly leading me to believe the seed itself that was used is never stored :( 

![image](https://github.com/user-attachments/assets/6f1b6507-7577-47d3-aab5-6af331d08f36)

Thank you for insight

**Comment by cubiq** [comment]
you can use the plot node to show the values, I'll think of something to have a better random number generation

**Comment by gonzalu** [comment]
I do use the plot node but only when generating tests :D 

I LOVE your nodes for production because of how easy and compact they make a workflow ;) So it would be great to record the actual seed in a widget, so it is stored in the image for future reference. 

And also, the "??" option you mentioned for constant random regeneration for back-to-back queue submits ;) 

You're awesome, Matteo! Thank you as always.
