### ISSUE TITLE
Multiple different Loras in LoRA for Flux Parameters

### ISSUE THREAD

**Issue by merlinvn** [cubiq/ComfyUI_essentials#85]
Hi, I saw that I can have multiple values for Lora strength. Just wonder if I can have a way to input multiple different LoRA names as well?

**Comment by cubiq** [comment]
yeah I'll add that option as well, it's a bit more complicated because of the loading/unloading

**Comment by merlinvn** [comment]
Thanks, can't wait to see that :D
