### ISSUE TITLE
[Question]  Does `SD3 Attention Seeker L/G` also work with SDXL?

### ISSUE THREAD

**Issue by LukeG89** [cubiq/ComfyUI_essentials#88]
Hi @cubiq, 

Since the `SD3 Attention Seeker L/G` node adjusts Clip L and Clip G, does that mean it could also work with SDXL?

I tried it and it does something, but I don't know if it's working properly or it's just a "side effect".

**Comment by cubiq** [comment]
technically yes, it should work, but I need to check, it might need more blocks
