### ISSUE TITLE
Ultimate SD Upscaler does not work with Clip Text Encode Sampler Params Node

### ISSUE THREAD

**Issue by gonzalu** [cubiq/ComfyUI_essentials#96]
After working with the developer for USDU thinking his node was not working with Flux or with Anything Everywhere nodes. However, it turns out that the problem is actually with the "Text Encode for Sampler Params" node.

I wondered if this was expected or not expected and can be made to work? 

Thank you. 

![image](https://github.com/user-attachments/assets/fcfa6107-f4b0-4296-899b-be678758aeb6)

**Comment by gonzalu** [comment]
And the error I was getting

```

**Comment by gonzalu** [comment]
![image](https://github.com/user-attachments/assets/839da337-bd5d-44d9-80fb-fe4a8c4f4a60)

**Comment by cubiq** [comment]
the text params is meant to worth with the params sampler, you have no reason to use it with anything else

**Comment by gonzalu** [comment]
Got it... thanks, Matteo.
